name: wbs-deploy

services:
  wikibase:
    ports:
      - 8880:80

  wdqs-frontend:
    ports:
      - 8834:80
  traefik:
    entrypoint: ["echo", "Service foo disabled"]


volumes:
  traefik-letsencrypt-data: null # remove this volume
